version: '2'
services:
  #######################################
  # PHP-FPM server
  #######################################
  phpserver:
#    image: php:fpm-alpine
    build:
      context: docker/
      dockerfile: php-typo3.Dockerfile
    links:
      - mysql
    volumes:
      - ./etc/php/typo3.ini:/usr/local/etc/php/conf.d/typo3.ini
    volumes_from:
      - storage

  #######################################
  # nginx web server
  #######################################
  nginx:
    image: nginx:stable-alpine
    links:
      - phpserver
    volumes:
      - ./etc/nginx/nginx2.conf:/etc/nginx/conf.d/default.conf
    volumes_from:
      - storage
    ports:
      - "80:80"
      - "443:433"
    environment:
#      - NGINX_HOST=typo3kurs.dev
      - NGINX_PORT=80

  #######################################
  # MySQL server
  #######################################
  mysql:
    image: wangxian/alpine-mysql
    volumes:
      - /app
    restart: always
#    volumes_from:
#      - storage
    env_file:
      - env/database.yml

  #######################################
  # phpMyAdmin
  #######################################
#  phpmyadmin:
#      image: phpmyadmin/phpmyadmin
#      links:
#        - mysql
#      ports:
#        - "8080:80"
#      environment:
#        - PMA_HOST=mysql
#      env_file:
#        - env/database.yml

  #######################################
  # Storage
  #######################################
  storage:
    image: busybox
#    build:
#      context: docker/storage/
#    restart: always
    volumes:
      - ./app:/var/www
#      - ./app/web:/usr/share/nginx/html
#volumes:
#  - db_data: /db
