#######################################
# Environment Configuration
#  - feel free to edit -
# -> for most changes you only have to
#         docker-compose up -d
#    to apply them
#######################################

#######################################
# PHP Debugger (xdebug|blackfire|none)

PHP_DEBUGGER=xdebug
XDEBUG_REMOTE_HOST=10.254.254.254
XDEBUG_REMOTE_AUTOSTART=1
XDEBUG_REMOTE_CONNECT_BACK=0

# This line isn't necessary but I keep it just a reminder to name the server properly in PhpStorm
PHP_IDE_CONFIG="serverName=docker"

#######################################
# Context environment

# TYPO3
TYPO3_CONTEXT=Development/Docker
